class ExportCountry
  include Mongoid::Document

  # used for both brands (countries of export) and distributors (countries of distribution)

  embedded_in :exportable, polymorphic: true

  field :country, type: String

  validates :country, presence: true

  # TOP 100 by GDP
	validates_inclusion_of :country, in: [ 
		"Algeria",
		"Angola",
		"Argentina",
		"Armenia",
		"Aruba",
		"Australia",
		"Austria",
		"Azerbaijan",
		"Bangladesh",
		"Belarus",
		"Belgium",
		"Bolivia",
		"Brazil",
		"Bulgaria",
		"Myanmar [Burma]",
		"Cameroon",
		"Canada",
		"Chile",
		"China",
		"Colombia",
		"Comoros",
		"Costa Rica",
		"Croatia",
		"Cuba",
		"Czech Republic",
		"Denmark",
		"Dominican Republic",
		"Ecuador",
		"Egypt",
		"El Salvador",
		"Ethiopia",
		"European Union",
		"Finland",
		"France",
		"Germany",
		"Ghana",
		"Greece",
		"Guatemala",
		"Hong Kong SAR China",
		"Hungary",
		"India",
		"Indonesia",
		"Iran",
		"Iraq",
		"Ireland",
		"Israel",
		"Italy",
		"Japan",
		"Kazakhstan",
		"Kenya",
		"Kuwait",
		"Lebanon",
		"Libya",
		"Lithuania",
		"Luxembourg",
		"Malaysia",
		"Mexico",
		"Morocco",
		"Nepal",
		"Netherlands",
		"New Zealand",
		"Norway",
		"Oman",
		"Pakistan",
		"Panama",
		"Papua New Guinea",
		"Paraguay",
		"Peru",
		"Philippines",
		"Poland",
		"Portugal",
		"Puerto Rico",
		"Qatar",
		"Romania",
		"Russia",
		"Saudi Arabia",
		"Serbia",
		"Singapore",
		"Slovakia",
		"Slovenia",
		"South Africa",
		"South Korea",
		"Spain",
		"Sri Lanka",
		"Sudan",
		"Sweden",
		"Switzerland",
		"Syria",
		"Taiwan",
		"Tanzania",
		"Thailand",
		"Tunisia",
		"Turkey",
		"Turkmenistan",
		"Uganda",
		"Ukraine",
		"United Arab Emirates",
		"United Kingdom",
		"United States",
		"Uruguay",
		"Uzbekistan",
		"Venezuela",
		"Vietnam",
		"Yemen"
	]

end
